name: marketplace
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  lottie: ^3.3.1
  flutter_svg: ^2.1.0
  connectivity_plus: ^6.1.4
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  geolocator: ^14.0.1
  logger: ^2.5.0
  go_router: ^15.1.3
  json_annotation: ^4.9.0
  add_to_cart_animation: ^2.0.4
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  pretty_dio_logger: ^1.4.0
  yandex_mapkit: ^4.1.0
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/
    - assets/videos/
